project:
  type: website
  output-dir: docs
  

website:
  title: "Zoe Gagalis"
  navbar:
   left:
    - href: index.qmd
      text: Home
    - Resume.qmd
    - Projects.qmd


format:
  html:
    theme: lux
    mainfont: arial
    fontcolor: "#000000"
    linkcolor: "#1BA749"
    css: styles.css
    monofont: courier new
    toc: true
    toc-location: right

editor: visual

