project:
  type: website
  output-dir: docs

website:
  title: "Zgagalis.github.io"
  image: zoe.jpeg
navbar:
  title: "Zoe Gagalis"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
    - text: "Resume"
      href: resume.html
    - text: "Projects"
      href: projects.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

